-- =====================================================================
-- Student planner app: Supabase schema
-- Run once in Supabase Dashboard -> SQL Editor -> New query -> Run.
-- Safe to read top to bottom: tables -> triggers -> indexes -> RLS.
-- =====================================================================

-- ---------- Helper: auto-update updated_at ----------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ---------- profiles (1 row per auth user) ----------
create table public.profiles (
  id                  uuid primary key references auth.users (id) on delete cascade,
  name                text,
  timezone            text not null default 'Asia/Jakarta',
  sleep_start         time not null default '23:00',
  sleep_end           time not null default '06:00',
  earliest_class_time time,
  work_hours_per_day  numeric(3,1) not null default 4
                      check (work_hours_per_day between 1 and 16),
  pace_factor         numeric(4,2) not null default 1.00
                      check (pace_factor between 0.5 and 3.0),
  onboarded           boolean not null default false,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

create trigger profiles_updated_at
  before update on public.profiles
  for each row execute function public.set_updated_at();

-- Auto-create a profile row whenever someone signs up
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, name)
  values (new.id, new.raw_user_meta_data ->> 'name');
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ---------- courses ----------
create table public.courses (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null default auth.uid() references auth.users (id) on delete cascade,
  name       text not null,
  color      text not null default '#6366f1',
  created_at timestamptz not null default now()
);

-- ---------- tasks (assignments, projects, exams, quizzes) ----------
create table public.tasks (
  id                uuid primary key default gen_random_uuid(),
  user_id           uuid not null default auth.uid() references auth.users (id) on delete cascade,
  course_id         uuid references public.courses (id) on delete set null,
  title             text not null,
  type              text not null default 'assignment'
                    check (type in ('assignment', 'project', 'exam', 'quiz', 'other')),
  deadline          timestamptz not null,
  grade_weight      numeric(5,2) not null default 0
                    check (grade_weight between 0 and 100),
  difficulty        smallint not null default 3
                    check (difficulty between 1 and 5),
  estimated_hours   numeric(4,1) not null default 1
                    check (estimated_hours > 0),
  priority_override smallint
                    check (priority_override between 1 and 5),
  is_group          boolean not null default false,
  status            text not null default 'todo'
                    check (status in ('todo', 'in_progress', 'done')),
  notes             text,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

create trigger tasks_updated_at
  before update on public.tasks
  for each row execute function public.set_updated_at();

-- ---------- commitments (fixed blocks: classes, meetings, church, etc.) ----------
-- day_of_week: 0 = Sunday ... 6 = Saturday (same as JavaScript Date.getDay())
-- Times are LOCAL wall-clock times in profiles.timezone.
create table public.commitments (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid not null default auth.uid() references auth.users (id) on delete cascade,
  title         text not null,
  category      text not null default 'other'
                check (category in ('class', 'org', 'church', 'committee', 'other')),
  is_recurring  boolean not null default true,
  day_of_week   smallint check (day_of_week between 0 and 6),
  specific_date date,
  start_time    time not null,
  end_time      time not null,
  created_at    timestamptz not null default now(),
  check (end_time > start_time),
  check (
    (is_recurring and day_of_week is not null)
    or (not is_recurring and specific_date is not null)
  )
);

-- ---------- sessions (planned work blocks generated by the planner) ----------
-- On replan: delete future rows with status 'planned', insert a new batch with
-- plan_version = previous max + 1. Rows with done/skipped stay as history.
create table public.sessions (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid not null default auth.uid() references auth.users (id) on delete cascade,
  task_id       uuid not null references public.tasks (id) on delete cascade,
  planned_start timestamptz not null,
  planned_end   timestamptz not null,
  status        text not null default 'planned'
                check (status in ('planned', 'done', 'skipped', 'moved')),
  ai_reason     text,
  plan_version  integer not null default 1,
  created_at    timestamptz not null default now(),
  check (planned_end > planned_start)
);

-- ---------- focus_logs (written by the focus timer) ----------
-- mode: 'strict'   = fullscreen, tab switches count as distractions
--       'flexible' = floating/minimized timer, only time is logged
create table public.focus_logs (
  id                uuid primary key default gen_random_uuid(),
  user_id           uuid not null default auth.uid() references auth.users (id) on delete cascade,
  task_id           uuid references public.tasks (id) on delete set null,
  session_id        uuid references public.sessions (id) on delete set null,
  mode              text not null default 'strict'
                    check (mode in ('strict', 'flexible')),
  started_at        timestamptz not null,
  ended_at          timestamptz not null,
  focused_minutes   numeric(6,1) not null check (focused_minutes >= 0),
  distraction_count integer not null default 0 check (distraction_count >= 0),
  created_at        timestamptz not null default now(),
  check (ended_at >= started_at)
);

-- ---------- Indexes ----------
create index tasks_user_deadline_idx      on public.tasks (user_id, deadline);
create index tasks_user_status_idx        on public.tasks (user_id, status);
create index commitments_user_idx         on public.commitments (user_id);
create index sessions_user_start_idx      on public.sessions (user_id, planned_start);
create index sessions_task_idx            on public.sessions (task_id);
create index focus_logs_user_started_idx  on public.focus_logs (user_id, started_at);
create index focus_logs_task_idx          on public.focus_logs (task_id);

-- ---------- Row Level Security ----------
-- RLS is what keeps users from reading each other's data, because the browser
-- talks to the database directly. Never disable it.

alter table public.profiles enable row level security;

create policy profiles_own on public.profiles
  for all to authenticated
  using (id = (select auth.uid()))
  with check (id = (select auth.uid()));

do $$
declare
  t text;
begin
  foreach t in array array['courses', 'tasks', 'commitments', 'sessions', 'focus_logs']
  loop
    execute format('alter table public.%I enable row level security', t);
    execute format(
      'create policy %I on public.%I for all to authenticated
         using (user_id = (select auth.uid()))
         with check (user_id = (select auth.uid()))',
      t || '_own', t
    );
  end loop;
end;
$$;

-- Make sure logged-in users can use the tables (RLS still restricts rows)
grant usage on schema public to authenticated;
grant select, insert, update, delete on all tables in schema public to authenticated;